# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_water_mainwd(object):
    def setupUi(self, water_mainwd):
        if not water_mainwd.objectName():
            water_mainwd.setObjectName(u"water_mainwd")
        water_mainwd.resize(1000, 822)
        water_mainwd.setContextMenuPolicy(Qt.DefaultContextMenu)
        water_mainwd.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.centralwidget = QWidget(water_mainwd)
        self.centralwidget.setObjectName(u"centralwidget")
        self.sel_input_btn = QPushButton(self.centralwidget)
        self.sel_input_btn.setObjectName(u"sel_input_btn")
        self.sel_input_btn.setGeometry(QRect(120, 10, 21, 28))
        self.sel_input_lbl = QLineEdit(self.centralwidget)
        self.sel_input_lbl.setObjectName(u"sel_input_lbl")
        self.sel_input_lbl.setGeometry(QRect(160, 10, 531, 21))
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 10, 81, 21))
        self.sel_output_btn = QPushButton(self.centralwidget)
        self.sel_output_btn.setObjectName(u"sel_output_btn")
        self.sel_output_btn.setGeometry(QRect(120, 50, 21, 28))
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 50, 81, 21))
        self.sel_output_lbl = QLineEdit(self.centralwidget)
        self.sel_output_lbl.setObjectName(u"sel_output_lbl")
        self.sel_output_lbl.setGeometry(QRect(160, 50, 531, 21))
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(30, 90, 101, 21))
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(30, 120, 101, 21))
        self.load_setting_btn = QPushButton(self.centralwidget)
        self.load_setting_btn.setObjectName(u"load_setting_btn")
        self.load_setting_btn.setGeometry(QRect(880, 90, 71, 28))
        self.dump_setting_btn = QPushButton(self.centralwidget)
        self.dump_setting_btn.setObjectName(u"dump_setting_btn")
        self.dump_setting_btn.setGeometry(QRect(880, 120, 71, 28))
        self.result_lbl = QTextBrowser(self.centralwidget)
        self.result_lbl.setObjectName(u"result_lbl")
        self.result_lbl.setGeometry(QRect(20, 590, 901, 181))
        self.exec_btn = QPushButton(self.centralwidget)
        self.exec_btn.setObjectName(u"exec_btn")
        self.exec_btn.setGeometry(QRect(930, 700, 61, 71))
        self.clear_output_btn = QPushButton(self.centralwidget)
        self.clear_output_btn.setObjectName(u"clear_output_btn")
        self.clear_output_btn.setGeometry(QRect(930, 590, 51, 31))
        self.clear_input_btn = QPushButton(self.centralwidget)
        self.clear_input_btn.setObjectName(u"clear_input_btn")
        self.clear_input_btn.setGeometry(QRect(30, 150, 101, 31))
        self.title_start_row = QLineEdit(self.centralwidget)
        self.title_start_row.setObjectName(u"title_start_row")
        self.title_start_row.setGeometry(QRect(140, 90, 41, 21))
        self.label_25 = QLabel(self.centralwidget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(200, 90, 21, 21))
        self.label_26 = QLabel(self.centralwidget)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(290, 90, 21, 21))
        self.title_start_column = QLineEdit(self.centralwidget)
        self.title_start_column.setObjectName(u"title_start_column")
        self.title_start_column.setGeometry(QRect(230, 90, 41, 21))
        self.label_27 = QLabel(self.centralwidget)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(290, 120, 21, 21))
        self.label_28 = QLabel(self.centralwidget)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(200, 120, 21, 21))
        self.data_start_column = QLineEdit(self.centralwidget)
        self.data_start_column.setObjectName(u"data_start_column")
        self.data_start_column.setGeometry(QRect(230, 120, 41, 21))
        self.data_start_row = QLineEdit(self.centralwidget)
        self.data_start_row.setObjectName(u"data_start_row")
        self.data_start_row.setGeometry(QRect(140, 120, 41, 21))
        self.label_29 = QLabel(self.centralwidget)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(710, 50, 81, 21))
        self.sel_output_file = QLineEdit(self.centralwidget)
        self.sel_output_file.setObjectName(u"sel_output_file")
        self.sel_output_file.setGeometry(QRect(790, 50, 161, 21))
        self.filter_fr_1 = QFrame(self.centralwidget)
        self.filter_fr_1.setObjectName(u"filter_fr_1")
        self.filter_fr_1.setGeometry(QRect(30, 190, 891, 121))
        self.filter_fr_1.setFrameShape(QFrame.StyledPanel)
        self.filter_fr_1.setFrameShadow(QFrame.Raised)
        self.filter_input_1 = QTextEdit(self.filter_fr_1)
        self.filter_input_1.setObjectName(u"filter_input_1")
        self.filter_input_1.setGeometry(QRect(50, 0, 831, 81))
        self.label_30 = QLabel(self.filter_fr_1)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(0, 10, 61, 21))
        self.sel_btn_lst_1 = QRadioButton(self.filter_fr_1)
        self.sel_btn_lst_1.setObjectName(u"sel_btn_lst_1")
        self.sel_btn_lst_1.setGeometry(QRect(280, 90, 115, 19))
        self.sel_btn_lst_1.setChecked(True)
        self.sel_btn_py_1 = QRadioButton(self.filter_fr_1)
        self.sel_btn_py_1.setObjectName(u"sel_btn_py_1")
        self.sel_btn_py_1.setGeometry(QRect(420, 90, 281, 19))
        self.sel_btn_regexp_1 = QRadioButton(self.filter_fr_1)
        self.sel_btn_regexp_1.setObjectName(u"sel_btn_regexp_1")
        self.sel_btn_regexp_1.setGeometry(QRect(740, 90, 131, 20))
        self.label_31 = QLabel(self.filter_fr_1)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 90, 81, 21))
        self.title_start_row_1 = QLineEdit(self.filter_fr_1)
        self.title_start_row_1.setObjectName(u"title_start_row_1")
        self.title_start_row_1.setGeometry(QRect(80, 90, 161, 21))
        self.filter_fr_2 = QFrame(self.centralwidget)
        self.filter_fr_2.setObjectName(u"filter_fr_2")
        self.filter_fr_2.setGeometry(QRect(30, 320, 891, 121))
        self.filter_fr_2.setFrameShape(QFrame.StyledPanel)
        self.filter_fr_2.setFrameShadow(QFrame.Raised)
        self.filter_input_2 = QTextEdit(self.filter_fr_2)
        self.filter_input_2.setObjectName(u"filter_input_2")
        self.filter_input_2.setGeometry(QRect(50, 0, 831, 81))
        self.label_32 = QLabel(self.filter_fr_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(0, 10, 61, 21))
        self.sel_btn_lst_2 = QRadioButton(self.filter_fr_2)
        self.sel_btn_lst_2.setObjectName(u"sel_btn_lst_2")
        self.sel_btn_lst_2.setGeometry(QRect(280, 90, 115, 19))
        self.sel_btn_lst_2.setChecked(True)
        self.sel_btn_py_2 = QRadioButton(self.filter_fr_2)
        self.sel_btn_py_2.setObjectName(u"sel_btn_py_2")
        self.sel_btn_py_2.setGeometry(QRect(420, 90, 281, 19))
        self.sel_btn_regexp_2 = QRadioButton(self.filter_fr_2)
        self.sel_btn_regexp_2.setObjectName(u"sel_btn_regexp_2")
        self.sel_btn_regexp_2.setGeometry(QRect(740, 90, 131, 20))
        self.label_33 = QLabel(self.filter_fr_2)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 90, 81, 21))
        self.title_start_row_2 = QLineEdit(self.filter_fr_2)
        self.title_start_row_2.setObjectName(u"title_start_row_2")
        self.title_start_row_2.setGeometry(QRect(80, 90, 161, 21))
        self.filter_fr_3 = QFrame(self.centralwidget)
        self.filter_fr_3.setObjectName(u"filter_fr_3")
        self.filter_fr_3.setGeometry(QRect(30, 450, 891, 121))
        self.filter_fr_3.setFrameShape(QFrame.StyledPanel)
        self.filter_fr_3.setFrameShadow(QFrame.Raised)
        self.filter_input_3 = QTextEdit(self.filter_fr_3)
        self.filter_input_3.setObjectName(u"filter_input_3")
        self.filter_input_3.setGeometry(QRect(50, 0, 831, 81))
        self.label_34 = QLabel(self.filter_fr_3)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(0, 10, 61, 21))
        self.sel_btn_lst_3 = QRadioButton(self.filter_fr_3)
        self.sel_btn_lst_3.setObjectName(u"sel_btn_lst_3")
        self.sel_btn_lst_3.setGeometry(QRect(280, 90, 115, 19))
        self.sel_btn_lst_3.setChecked(True)
        self.sel_btn_py_3 = QRadioButton(self.filter_fr_3)
        self.sel_btn_py_3.setObjectName(u"sel_btn_py_3")
        self.sel_btn_py_3.setGeometry(QRect(420, 90, 281, 19))
        self.sel_btn_regexp_3 = QRadioButton(self.filter_fr_3)
        self.sel_btn_regexp_3.setObjectName(u"sel_btn_regexp_3")
        self.sel_btn_regexp_3.setGeometry(QRect(740, 90, 131, 20))
        self.label_35 = QLabel(self.filter_fr_3)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 90, 81, 21))
        self.title_start_row_3 = QLineEdit(self.filter_fr_3)
        self.title_start_row_3.setObjectName(u"title_start_row_3")
        self.title_start_row_3.setGeometry(QRect(80, 90, 161, 21))
        self.open_when_fin_btn = QCheckBox(self.centralwidget)
        self.open_when_fin_btn.setObjectName(u"open_when_fin_btn")
        self.open_when_fin_btn.setGeometry(QRect(970, 650, 21, 21))
        self.open_when_fin_btn.setChecked(True)
        self.label_36 = QLabel(self.centralwidget)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(930, 630, 61, 41))
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(330, 80, 111, 51))
        self.filter_result_items = QTextEdit(self.centralwidget)
        self.filter_result_items.setObjectName(u"filter_result_items")
        self.filter_result_items.setGeometry(QRect(450, 90, 241, 91))
        water_mainwd.setCentralWidget(self.centralwidget)
        self.label_36.raise_()
        self.sel_input_btn.raise_()
        self.sel_input_lbl.raise_()
        self.label_18.raise_()
        self.sel_output_btn.raise_()
        self.label_19.raise_()
        self.sel_output_lbl.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.load_setting_btn.raise_()
        self.dump_setting_btn.raise_()
        self.result_lbl.raise_()
        self.exec_btn.raise_()
        self.clear_output_btn.raise_()
        self.clear_input_btn.raise_()
        self.title_start_row.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.title_start_column.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.data_start_column.raise_()
        self.data_start_row.raise_()
        self.label_29.raise_()
        self.sel_output_file.raise_()
        self.filter_fr_1.raise_()
        self.filter_fr_2.raise_()
        self.filter_fr_3.raise_()
        self.open_when_fin_btn.raise_()
        self.label_20.raise_()
        self.filter_result_items.raise_()
        self.menubar = QMenuBar(water_mainwd)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 26))
        water_mainwd.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(water_mainwd)
        self.statusbar.setObjectName(u"statusbar")
        water_mainwd.setStatusBar(self.statusbar)

        self.retranslateUi(water_mainwd)

        QMetaObject.connectSlotsByName(water_mainwd)
    # setupUi

    def retranslateUi(self, water_mainwd):
        water_mainwd.setWindowTitle(QCoreApplication.translate("water_mainwd", u"\u8868\u683c\u7b5b\u9009\u5668", None))
        self.sel_input_btn.setText(QCoreApplication.translate("water_mainwd", u"...", None))
        self.sel_input_lbl.setText(QCoreApplication.translate("water_mainwd", u"water-core", None))
        self.label_18.setText(QCoreApplication.translate("water_mainwd", u"\u8f93\u5165\u9009\u62e9:", None))
        self.sel_output_btn.setText(QCoreApplication.translate("water_mainwd", u"...", None))
        self.label_19.setText(QCoreApplication.translate("water_mainwd", u"\u8f93\u51fa\u8def\u5f84:", None))
        self.sel_output_lbl.setText(QCoreApplication.translate("water_mainwd", u"water-core", None))
        self.label_23.setText(QCoreApplication.translate("water_mainwd", u"\u6807\u9898\u8d77\u59cb\u4f4d\u7f6e:", None))
        self.label_24.setText(QCoreApplication.translate("water_mainwd", u"\u6570\u636e\u8d77\u59cb\u4f4d\u7f6e:", None))
        self.load_setting_btn.setText(QCoreApplication.translate("water_mainwd", u"\u8f7d\u5165\u914d\u7f6e", None))
        self.dump_setting_btn.setText(QCoreApplication.translate("water_mainwd", u"\u5bfc\u51fa\u914d\u7f6e", None))
        self.exec_btn.setText(QCoreApplication.translate("water_mainwd", u"\u6267\u884c", None))
        self.clear_output_btn.setText(QCoreApplication.translate("water_mainwd", u"clear", None))
        self.clear_input_btn.setText(QCoreApplication.translate("water_mainwd", u"\u6e05\u7a7a\u8f93\u5165", None))
        self.title_start_row.setText(QCoreApplication.translate("water_mainwd", u"1", None))
        self.label_25.setText(QCoreApplication.translate("water_mainwd", u"\u884c", None))
        self.label_26.setText(QCoreApplication.translate("water_mainwd", u"\u5217", None))
        self.title_start_column.setText(QCoreApplication.translate("water_mainwd", u"1", None))
        self.label_27.setText(QCoreApplication.translate("water_mainwd", u"\u5217", None))
        self.label_28.setText(QCoreApplication.translate("water_mainwd", u"\u884c", None))
        self.data_start_column.setText(QCoreApplication.translate("water_mainwd", u"1", None))
        self.data_start_row.setText(QCoreApplication.translate("water_mainwd", u"2", None))
        self.label_29.setText(QCoreApplication.translate("water_mainwd", u"\u8f93\u51fa\u8868\u540d:", None))
        self.sel_output_file.setText(QCoreApplication.translate("water_mainwd", u"Result", None))
        self.label_30.setText(QCoreApplication.translate("water_mainwd", u"\u6761\u4ef61:", None))
        self.sel_btn_lst_1.setText(QCoreApplication.translate("water_mainwd", u"\u5217\u8868\u7b5b\u9009", None))
        self.sel_btn_py_1.setText(QCoreApplication.translate("water_mainwd", u"python\u6761\u4ef6\u8868\u8fbe\u5f0f(\u201cX\u201d\u8868\u793a\u6570\u636e)", None))
        self.sel_btn_regexp_1.setText(QCoreApplication.translate("water_mainwd", u"\u6b63\u5219\u8868\u8fbe\u5f0f", None))
        self.label_31.setText(QCoreApplication.translate("water_mainwd", u"\u5217\u540d\u79f0:", None))
        self.title_start_row_1.setText(QCoreApplication.translate("water_mainwd", u"\u5408\u540c\u53f7", None))
        self.label_32.setText(QCoreApplication.translate("water_mainwd", u"\u6761\u4ef62:", None))
        self.sel_btn_lst_2.setText(QCoreApplication.translate("water_mainwd", u"\u5217\u8868\u7b5b\u9009", None))
        self.sel_btn_py_2.setText(QCoreApplication.translate("water_mainwd", u"python\u6761\u4ef6\u8868\u8fbe\u5f0f(\u201cX\u201d\u8868\u793a\u6570\u636e)", None))
        self.sel_btn_regexp_2.setText(QCoreApplication.translate("water_mainwd", u"\u6b63\u5219\u8868\u8fbe\u5f0f", None))
        self.label_33.setText(QCoreApplication.translate("water_mainwd", u"\u5217\u540d\u79f0:", None))
        self.title_start_row_2.setText("")
        self.label_34.setText(QCoreApplication.translate("water_mainwd", u"\u6761\u4ef63:", None))
        self.sel_btn_lst_3.setText(QCoreApplication.translate("water_mainwd", u"\u5217\u8868\u7b5b\u9009", None))
        self.sel_btn_py_3.setText(QCoreApplication.translate("water_mainwd", u"python\u6761\u4ef6\u8868\u8fbe\u5f0f(\u201cX\u201d\u8868\u793a\u6570\u636e)", None))
        self.sel_btn_regexp_3.setText(QCoreApplication.translate("water_mainwd", u"\u6b63\u5219\u8868\u8fbe\u5f0f", None))
        self.label_35.setText(QCoreApplication.translate("water_mainwd", u"\u5217\u540d\u79f0:", None))
        self.title_start_row_3.setText("")
        self.open_when_fin_btn.setText("")
        self.label_36.setText(QCoreApplication.translate("water_mainwd", u"\u5b8c\u6210\u540e\n"
"\u6253\u5f00:", None))
        self.label_20.setText(QCoreApplication.translate("water_mainwd", u"\u7b5b\u9009\u7ed3\u679c\u4fdd\u5b58\n"
"\u9879\u76ee(\u6362\u884c\u5206\u9694):", None))
        self.filter_result_items.setHtml(QCoreApplication.translate("water_mainwd", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u5408\u540c\u53f7</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u4ea7\u54c1\u540d\u79f0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u5408\u540c\u578b\u53f7</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u53d1\u8d27\u6570\u91cf</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; "
                        "-qt-block-indent:0; text-indent:0px;\">\u5408\u540c\u5355\u4ef7</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u51fa\u5382\u7f16\u53f7</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\u673a\u67dc</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
    # retranslateUi

